# Generated by Django 3.1.6 on 2021-05-06 03:36

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20210214_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.CharField(default='unknown', max_length=256, verbose_name='event name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='event_dates',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.DateTimeField(default=None, null=True), size=None, verbose_name='dates/times of the event'),
        ),
    ]
