# Generated by Django 3.1.6 on 2021-05-06 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_remove_event_event_dates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='flyer',
        ),
        migrations.CreateModel(
            name='Flyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Flyer image')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.event')),
            ],
        ),
    ]
