# Generated by Django 3.1.6 on 2021-05-08 20:49

from django.db import migrations, models
import django.db.models.deletion
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20210506_1846'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='color name')),
                ('color', website.models.ColorField(default='#005182', max_length=10, verbose_name='color')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='theme_color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='website.themecolor'),
        ),
    ]
