# Generated by Django 3.1.6 on 2021-05-10 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20210508_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Setlist image')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.event')),
            ],
        ),
        migrations.CreateModel(
            name='Teaser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Teaser image')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.event')),
            ],
        ),
        migrations.DeleteModel(
            name='Flyer',
        ),
    ]
