# Generated by Django 3.1.6 on 2021-02-15 03:30

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_dates',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 6, 0, tzinfo=utc), null=True), size=None, verbose_name='dates/times of the event'),
        ),
    ]
